# Generated by Django 4.1.3 on 2022-12-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tempat', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('lokasi', models.TextField()),
                ('kategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywisata.kategori')),
            ],
        ),
    ]
