# Generated by Django 4.1.3 on 2022-12-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywisata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': 'Kategori'},
        ),
        migrations.AddField(
            model_name='artikel',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
