# Generated by Django 4.1.3 on 2022-12-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywisata', '0002_alter_artikel_options_alter_kategori_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='img',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='published',
        ),
    ]
