# Generated by Django 4.1.3 on 2022-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywisata', '0003_remove_artikel_img_remove_artikel_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
